# Generated by Django 4.0.1 on 2022-02-01 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeedBack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Имя')),
                ('email', models.EmailField(max_length=254, verbose_name='Почта')),
                ('phone', models.IntegerField(max_length=12, verbose_name='Телефон (без +)')),
                ('message', models.TextField(verbose_name='Отзыв')),
            ],
        ),
    ]
