# Generated by Django 4.0.2 on 2022-02-18 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_feedback_options_alter_feedback_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TartipCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Тип продукции')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Тип',
                'verbose_name_plural': 'Типы',
            },
        ),
        migrations.AlterField(
            model_name='feedback',
            name='message',
            field=models.TextField(verbose_name='Ваше сообщение или заказ'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='phone',
            field=models.CharField(default='', max_length=13, verbose_name='Телефон'),
        ),
        migrations.CreateModel(
            name='Tartip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='Название')),
                ('description', models.CharField(max_length=50, verbose_name='Описание')),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.tartipcategory')),
            ],
            options={
                'verbose_name': 'Продукция',
                'verbose_name_plural': 'Продукция',
            },
        ),
    ]
